version: '3.8'
services:
  zookeeper2:
    image: zookeeper:3.9
    container_name: zookeeper2
    hostname: zookeeper2
    healthcheck:
      test: ["CMD-SHELL", "zkCli.sh -server zookeeper2:2181 ls /"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      clickhouse-network2:
        ipv4_address: 172.24.0.10
  clickhouse2_01:
    image: clickhouse/clickhouse-server:25.4-alpine
    container_name: clickhouse2_01
    hostname: clickhouse01
    networks:
      clickhouse-network2:
        ipv4_address: 172.24.0.11
    ports:
      - "8133:8123"
      - "9010:9000"
    volumes:
      - ./clickhouse01:/etc/clickhouse-server
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --host clickhouse01 --query 'SELECT 1'"]
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_SKIP_USER_SETUP: 1
    depends_on:
      zookeeper2:
        condition: service_healthy
  clickhouse2_02:
    image: clickhouse/clickhouse-server:25.4-alpine
    container_name: clickhouse2_02
    hostname: clickhouse02
    networks:
      clickhouse-network2:
        ipv4_address: 172.24.0.12
    ports:
      - "8134:8123"
      - "9011:9000"
    volumes:
      - ./clickhouse02:/etc/clickhouse-server
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --host clickhouse02 --query 'SELECT 1'" ]
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_SKIP_USER_SETUP: 1
    depends_on:
      zookeeper2:
        condition: service_healthy

networks:
  clickhouse-network2:
    name: clickhouse-network2
    ipam:
      config:
        - subnet: 172.24.0.0/24
